### ISSUE TITLE
Client crash looking at pretty fairies

### ISSUE THREAD

**Issue by Ozurian** [RootsTeam/Roots#234] opened 2017-07-01 13:56 UTC
When looking at one of these fancy new fairy mobs having waila active, client crashed immediately.
Seems to be an issue in the NBT saving function here, since it complains of not being able to cast BlockPos to bool.

The offending line referred in crash is:
https://github.com/RootsTeam/Roots/blob/master/src/main/java/teamroots/roots/entity/EntityFairy.java#L367

Crash report:
https://gist.github.com/Ozurian/b32fa7d4b4e1d0153957bafc9177064b

Roots version: 2.0.024
Forge: 1.11.2-13.20.1.2388

**Comment by elucent** [comment] 2017-07-01 14:55
I'm really not sure what's going wrong here. Does it happen reliably?

**Comment by Ozurian** [comment] 2017-07-01 16:31
It's definitely a kind of strange crash fore sure. When going back and looking at the same fairy after restarting and logging in again it worked fine. If I recall correctly this fairy in question had pretty much just spawned in after I ran over to greet these fairies that had spawned in next to my base, then immediate crash.

I'll try to run around and find some more and keep an eye out for some more details on when exactly it happens vs not.

**Comment by QuarterAnimal** [comment] 2017-07-01 19:04
I'm getting a similar client crash in EntityFairy.java, line 100, where getDataManager.get(variant) seems to be returning a BlockPos instead of an int and the type cast fails. My guess is the NBT structure changed in this last update, and any lingering fairies spawned prior to 2.0.024 can (will?) cause trouble in the new code when their chunks are loaded. Once I kill off all the old fairies--or start a new world--newly spawned ones don't appear to trigger the error.

**Comment by DoomSquirter** [comment] 2017-07-02 07:17
just to throw my 2 cents in.
running roots-2-0.024 as well, on a server.  My base is between two fairy pools and I have had zero issues with them thus far.  We updated earlier, I logged in, was on for a couple hours real time, so many days had passed in game.  no issues.  I just tried logging into server and got similar crash each time I tried to login.  night time or day time, they don't seem to despawn I guess unless I am in proximity?

pertinent snippet:
Description: Ticking entity
java.lang.ClassCastException: net.minecraft.util.math.BlockPos cannot be cast to java.lang.Integer
	at teamroots.roots.entity.EntityFairy.getRed(EntityFairy.java:100)
	at teamroots.roots.entity.EntityFairy.func_70071_h_(EntityFairy.java:149)

having an admin do a /kill @e[type=roots:Fairy] did not help either, at this point, locked out of server and afraid for someone to go to my base to try to help to have them locked out as well.

**Comment by elucent** [comment] 2017-07-02 08:20
@DoomSquirter can you still reliably reproduce this issue? If so, try this build: 
https://dl.dropboxusercontent.com/s/yjxqcpl8ot9ky4i/roots-2-0.025.jar?dl=0

This might just be a trial and error fix. :/

If you're on Discord I can talk to you more real-time, though it's 4:20 AM right now (heh) and I'll be sleeping for the next little while.

**Comment by elucent** [comment] 2017-07-02 08:22
Derp. Accidentally closed. That's the 4 am talking. :P

**Comment by DoomSquirter** [comment] 2017-07-02 08:31
addendum to above.  we tried everything.  Only fix was to revert to previous version of roots.

**Comment by DoomSquirter** [comment] 2017-07-02 08:33
oh sorry, my client didn't update.  Yeah, I'm on discord.  lemme talk to admin to see if she's amenable to trying a fix.

**Comment by DoomSquirter** [comment] 2017-07-02 08:54
since we've already fixed my current issue, I'm probably not the one to ask to verify now.  There's no reliable way to reproduce that issue since like I said, I spent a good hour or so in my base after we had updated without having any issues, and I was working right next to the pool fairy's were generating from.  The only factor involved, was for me to login to server while it was night time and getting that error message each time I subsequently tried logging in, even after waiting for daytime.  Assuming that one fairy was spawned during my initial login that was causing the issue and it didn't despawn since I never completed any subsequent logins.  

I'm lurking in your discord.  feel free to ping me if you have any further questions.

**Comment by austragus** [comment] 2017-07-04 02:03
I am facing this issue as well. There is the crash log.

https://pastebin.com/JHmdqTq4

**Comment by elucent** [comment] 2017-07-04 02:23
@austragus try that jar I posted a little bit up. Confusing bug.

**Comment by Mailleweaver** [comment] 2017-07-04 15:13
I just had the same random crash. Crash reports look almost identical. Logging back in to the server just caused another client crash. Restarting the server allowed me to log back in without crashing. My server mates and I have been using this version of Roots for four days without problems until today.

Unfortunately I can't reproduce the fault. If I get it again, I'll try booting my client with the jar above.

https://pastebin.com/ZMm3UU2k

**Comment by Ozurian** [comment] 2017-07-04 15:28
Not managed to make this one reoccur yet, but I found some more serious trouble using the 2.0.024 version - crafting in circles doesn't work because there is no moonlight appearing at all.. (ran around and tried many circles to no avail) downgrading to 2.0.020 made it work again in the first circle I tried, so going to test a few other scenarios like the test build you added there :)

As previously mentioned above it definitely seems likely that this only affects persisting fairies from before the upgrade, having the order of their data changed and erroring out. No matter how many new ones I spawned I was unable to reproduce the issue running v. 2.0.024 

Update:
Tested an upgrade from a world with version .20 -> .25 now to see if there is any difference in regards to fairies and the crash and so far didn't see any upon finding some fairies. But in .25 as well the moonlight doesn't appear, as well as there being a warning on missing blocks just like .24.

In the end I guess I'll just use .20 for now since that one worked fine :)

**Comment by elucent** [comment] 2017-07-04 16:25
Okay, thanks for letting me know. I'll release the new version just in case it fixes things. Unfortunately this bug might just require some server restarting or something.

**Comment by Mailleweaver** [comment] 2017-07-06 08:38
Well, I just got this bug again for the first time since my last post (playing nearly every day in the same area with 5 fairy pools) but unfortunately can't check if the new version fixes the client crash since I can't connect to the server (running .024) while my client runs .025. And restarting the server to put the new version on it would clear the error whether I put the new version on it or not.

It seems that the crash is purely client side though it's in response to something the server is doing. Another player on my server experienced this issue a day or two ago while I was online, and I had no problems where I was (in the area where I crashed before) while he crashed repeatedly. At the time I didn't think to go to his area to see if it caused me crashes, too; I just restarted the server to clear whatever condition was causing his client crashes and he hasn't had an issue since.

Would it be possible to make a client version for testing that doesn't care if it matches the server, or is this issue really dependent on matching code on both sides? Since there seems to be no way to reliably recreate the fault condition, it would be helpful to be able to avoid restarting the server to test the new version when the fault presents itself; otherwise there's no way to be sure that it's fixed without putting the new version on both client and server and just playing for weeks to see if the fault recurs.

**Comment by elucent** [comment] 2017-07-06 17:07
Been talking this over with some people and this is likely not a Roots 2 bug. See here for an explanation https://github.com/Vazkii/Botania/issues/2114#issuecomment-272708867.

This is some kind of mod conflict, and you'll need to somehow track down what other mod is screwing with the DataWatcher. I do not believe there is anything I can do on my side.

**Comment by Mailleweaver** [comment] 2017-07-07 00:03
Is there a way for me, as a non-developer, to check if a mod does that? I have a list of mods that were updated/added with the update of the pack that I'm using where the crashes started, so that's probably a good place to start.

**Comment by elucent** [comment] 2017-07-07 00:45
Not really. It's a very tricky bug to track down unfortunately. :/

**Comment by Mailleweaver** [comment] 2017-07-07 01:11
Would EntityDataManager.func likely be in the code of the offending mod? I went to the github page for each of the open source mods on my list and did a search this repository for "EntityDataManager.func" and got no results. I'm wondering if that means it's in one of the closed source mods or if it could be different code causing the same issue.

**Comment by austragus** [comment] 2017-07-07 03:02
I have used the v25 jar for a few days now, and haven't run into a crash yet. The last time it happened was starting a new world with the same seed.

**Comment by elucent** [comment] 2017-07-07 22:58
Oh, really? That's good then, I didn't expect it to have any impact. I'll release that version formally soonish.

**Comment by Mailleweaver** [comment] 2017-07-08 01:11
The people over at Animania have looked into it some and have found that they'll have to make a change to the way they use EntityDataManager. That's a potential cause of some of this. I'm wondering if there may be another mod at fault as well since Animania is not in the first crash report on this thread.

My next guess is Blood Magic since it's common to all of us, my list of mods that were updated when the problem first showed up, and the changelog gives me a feeling that it could have included something related. It's just a hunch, but my years fixing copiers has taught me to follow my hunches when dealing with systems I don't fully understand; they usually lead me to something useful. I'll write up a request for them to look into it, too.

**Comment by Fundryi** [comment] 2017-07-23 12:24
Just wanna give headsup that I have the same Issue on 1.12

Crash: https://gist.github.com/Fundryi/33762b442a9dafbab09b90c515bfb5c5

**Comment by elucent** [comment] 2017-09-17 04:00
Will be fixed in next update.

**Closed by elucent** 2017-09-17 04:00 UTC
Labels: 1.11.2, bug
