### ISSUE TITLE
[1.12] cascading worldgen lag

### ISSUE THREAD

**Issue by Morpheus1101** [RootsTeam/Roots#240] opened 2017-07-16 13:23 UTC
Each time someone on the server goes through a new chunk, the below msg gets spammed along with other mods doing the same thing.

[FML]: Roots 2 loaded a new chunk (-524, 50 Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by elucent** [comment] 2017-09-17 03:59
Duplicate of #229

**Closed by elucent** 2017-09-17 03:59 UTC
