### ISSUE TITLE
Chunk crash when do Ritual for Sprites or Monster (Single & Multiplayer)

### ISSUE THREAD

**Issue by KetMaliss** [RootsTeam/Roots#160] opened 2016-12-20 10:18 UTC
When i try to do the ritual for Monster or Sprite, the Chunk crashes, i tried this in a Singleplayer Game with the same result. When i relog, the Monster or Sprite is there. We use the Hermitpack (Version 1.51), with Draconic Evolution.

**Comment by kingOlegos** [comment] 2016-12-20 15:05
I'm having the same problem. I don't think it's caused by Draconic Evolution, because I'm not using it.

**Comment by VallenFrostweaver** [comment] 2016-12-20 17:49
This issue has since been fixed with an updated version of Roots (0.208). Regrettably, HermitPack hasn't updated this yet.

**Comment by KetMaliss** [comment] 2016-12-20 18:45
Ok, thx for the answer, Server will be updatet soon.

**Closed** 2016-12-21 19:59 UTC
